---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-tls
  namespace: harbor
type: kubernetes.io/tls
stringData:
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCkf6h8YuzyRtTc
    MgeUExI/K1pKu2IWa1jj0qiYqkvGt04xVCJwnlcU2hCDx0307/SXZg/H19V0Emot
    729qTShFN7q8vbzfXCzXznp6v0xnyin/2lCgdKGkv87IYanO3tDQkGUlgY9dSKx9
    tztu6YitLsSpJXnnzcCLk0NmWxPdGM707imffU62QlPMyeukvb7ZJlaO/0lHzGCL
    XKgYQNI30H4YNxhWJun0ZIvIaYFZ6KFfzKZlyE3awfeuvQsUTPYXf9PZSMt9qvt9
    1g00bw6F6nY6zV1FKtnyEOwkGFzA8XPn/IT7UoZUljic97PLfx36Tp/B2mjTSY5L
    4JDRWofWmvuM+QEb1hEcPYkTgSv/tCJ2WY9QTOwrte341dQ3JUvoHN9CktRLCUDk
    luivb3pmjvslpNxMzBxFuYZb97hgLXFima8Sx6Xxa9Kd+Iv4+ZP2WBQKQlnSkmgx
    m7ooxWpOwFxP9dpOFIpjcXowNdCdGbyN+I6Wlaq9Q5X2hs2Rc0mRaIdUnxDx6kTK
    qfzA65xW3FG5d89Te6c46Lgl/CnEacPlbro7L3XdpZHUmTcsolcNTC86ufXeVy5c
    6g9ogyg5RVs2KCq2MCTk9YTCHPyUDhc9m/6Ub9P5hG9zfQql4zq5YsBS/8Ko8jNy
    bx9ri9Emaxt6gwNSMNdoWpo25EdoGQIDAQABAoICAAe6WD57tpj32zvQUosneDXP
    12k9CLHNROWdub5DpdVbOt5WDwYjvNXlxrKCKaHmUfh42tNEdaqDIPTb05ahXaZ0
    JJ7a+mVd4wdtE6jyQBMngWCb2ionld5zr7G55ix/Sue5bjRcXqapvtzAamzephqe
    C1l3lr9dQFHuTv4fLOg3/aUDuUsyVlZ5TY7d35Gjjl83jgfKwMpm32mR+/L5EfHS
    /CbZaRhxseUBgjrzO0NE4AFBpSw77u27gLjMoxlxjNAezmOIqB1VFoUwtKRwITUJ
    BkPjQ6H3uORxMhQiBt1+RQ0yz5vaTSWVJxS3Yv1zkS4iBR7/dT7pLOOt/u+u5URh
    ldyul44trq8cQcMmCVBfk6wYBY25ta1YoYCKOEgvMwS1NNeQysmBT6kVHWL52Yxi
    HB8Zq4JEssXxi5uT2uqHHe7tZ7EUIWWReIQM1w0oI5JqcOiVzB7cak60Xj/ogG47
    KrCm0IsEqahcldiUbhu1lVEy7KRzLk5DsR16DbUcD8hxvBMbbEwFiFcZxjq5cawa
    NVNAL5Npv9jaF0ngsfokMFXXe+mljhIQO2wzv73cmBx45P8xYSHWm5BDSmCLKDOS
    R0hed/yUOdbwHFNrD0785KlfU0K2sPpt5pUZx2pgowEm2DHKYU5VtizzdGmt3gGu
    R+gSqJrv1vddWKmr/sbXAoIBAQDYJta8PdJAz9Y+5WKBGWx5H8FZ/4bqYJPryJG8
    9fqa3zeUlKQGnHWLQ2YWwh9O8ru1E8cdg+68MnNloKxzXnpCUxGzP61YTR+QJRIW
    u9L9+5Dn7cQCkDSraz0qSEvf5aKbTb4qlOxkes/0X6QDwDyrnQjrpnHI7HGbyJo8
    xxRBYQxaIvY+Uu5ILcys3HtGQzW4Os9hJELy/BN3l86+sv6MH5d7JbF16vxCIk2I
    reDwdRVbe39nfcq53O3TdZw21JsZ2KRkIynQMTjw+KmOrOr/T/R3CdJAXtFVa+R3
    cOBcN8H3LoL7PBoXfhqIg69lXGXmtTg8AwpS6nZG7I7yr6HDAoIBAQDC0xUEN0/3
    NxdTXUXIiFWng/JtxsTNwmWcl+lbu/WohXKjL5LQCbCJ0zjXR2KchBmwTS5K0WUg
    XAObtJcTD+DJx3a+/8HMxCXVy4whMQCsx4JUwLv0z+xERD6f5puhxAaoU7j03t+g
    ZoUDt68xIjpmzcoECXgPUu2EkjbRGTKdvy4/crJ7kMk8UFbvJL+RjbeJ4gyfNlgA
    JR3TOs/x9qQYAAO+IuCMWN7lgjMq3w3VDoREOilaAi6Ma1+GIfehJTO6VFq2529r
    532uN6DtwrE0Dt5Fpmppk4YYkBfao6rG6DXV6lAS5vp5fkIFnsI9A/GCXnD1seQ+
    8KgMf2Hn4fTzAoIBAHG19O+woiRgcjhCWlDKPCt4TjJ3X9V7GzZGHI1I5h6FYWrz
    y1qDAr9RpKpCU1AoGCGJlw1q87Pj4ptLLI3A3RZ5Nu2SiTHT2M/vAJYfFz9wEWpB
    xgUHMf4f+1x8DhZqauHCw1EJaVbu2OmZSuKCRiiOAzxdIqzt3lJy9NkWbgx67pGY
    pOximmI0XeFuWBe9kcwqfCCBgAruG5ulrCjcZ1b1463wRWxgQ3bTLvDBcH1vSt4G
    mR6rqXOfyymcTKL3s+Sj+M+JRBz3WBpE5oZdZ38K4/OfohElEIEcsmM3aYB6ALt1
    p4hdtOg4+eJpTGNJeX4mRcAkZVD7cV+cYRNA3BsCggEAQI5ZJHB/mtcyb3k0qmIi
    n8NlDWMTy2pi6SSdOrxphlHRzqjw6OaNDN5ks1EAKATNzlGEyV3hOHvE5k9M0BAu
    2C2z904gFY3ZS6KK6GSoaJgjY5oJrfFHxMcoSSvM3ilqW1SCsQE48JmH8ddnwcwp
    te7yxautkMZV1dvtNhQ3ZXX4CSYkZjVvuQCWDeALalufOZ0huY/0UPf7jgaq6O5l
    KV633sUHyvmXwk0GT2ph1vtccI8lLKIUcosRuAyBVXBSV6ej939wuDyYtKXSOXaN
    6UYT+NhP4nPztyfn/5bD++zuCdf+eIT48lEX52zXyAgKerx4ibFMhF6SELIU6xVA
    aQKCAQBn/56BA4t4o1DWwXw8AactfLeJxxhNlKeWDp218LLtgkRBAOiOlT189/2z
    sy/EksHvZxwzsaAMtYCMtkS7KYoqbwcUhexehfpQEogeCk2kEGEt74kTx+0kLqhK
    eE2qqxyN4FNZBCRAVcqy1CgnfMlwQFIxcb16yelP49ypJzJnD7szVXyK6+PuxvQi
    rOZUI1c46nnLOIMdqxmJalEBIxmaYk1+F3wgsBxsdZVwE9SAJZ95AXa82QOv9ZGR
    1i47GCSdZk5xhTeIn/czbFOfG6RHYSYBIrBnK5U1v27jzorLCO7qCAxtNPXWnfIj
    CfW/U+dHU889zRwXJhMvcxgWp/8Z
    -----END PRIVATE KEY-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFYzCCA0ugAwIBAgIUWsM32XDRRCKCGgdwPiqYsR5WebMwDQYJKoZIhvcNAQEL
    BQAwKjEoMCYGA1UEAwwfaGFyYm9yLmhhcmJvci5zdmMuY2x1c3Rlci5sb2NhbDAg
    Fw0yNTEyMDEwMDMwMjVaGA8yMDUzMDQxNzAwMzAyNVowKjEoMCYGA1UEAwwfaGFy
    Ym9yLmhhcmJvci5zdmMuY2x1c3Rlci5sb2NhbDCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAKR/qHxi7PJG1NwyB5QTEj8rWkq7YhZrWOPSqJiqS8a3TjFU
    InCeVxTaEIPHTfTv9JdmD8fX1XQSai3vb2pNKEU3ury9vN9cLNfOenq/TGfKKf/a
    UKB0oaS/zshhqc7e0NCQZSWBj11IrH23O27piK0uxKkleefNwIuTQ2ZbE90YzvTu
    KZ99TrZCU8zJ66S9vtkmVo7/SUfMYItcqBhA0jfQfhg3GFYm6fRki8hpgVnooV/M
    pmXITdrB9669CxRM9hd/09lIy32q+33WDTRvDoXqdjrNXUUq2fIQ7CQYXMDxc+f8
    hPtShlSWOJz3s8t/HfpOn8HaaNNJjkvgkNFah9aa+4z5ARvWERw9iROBK/+0InZZ
    j1BM7Cu17fjV1DclS+gc30KS1EsJQOSW6K9vemaO+yWk3EzMHEW5hlv3uGAtcWKZ
    rxLHpfFr0p34i/j5k/ZYFApCWdKSaDGbuijFak7AXE/12k4UimNxejA10J0ZvI34
    jpaVqr1DlfaGzZFzSZFoh1SfEPHqRMqp/MDrnFbcUbl3z1N7pzjouCX8KcRpw+Vu
    ujsvdd2lkdSZNyyiVw1MLzq59d5XLlzqD2iDKDlFWzYoKrYwJOT1hMIc/JQOFz2b
    /pRv0/mEb3N9CqXjOrliwFL/wqjyM3JvH2uL0SZrG3qDA1Iw12hamjbkR2gZAgMB
    AAGjfzB9MB0GA1UdDgQWBBS3/XWzeao1iBT3gDLQtBtoz5SXoDAfBgNVHSMEGDAW
    gBS3/XWzeao1iBT3gDLQtBtoz5SXoDAPBgNVHRMBAf8EBTADAQH/MCoGA1UdEQQj
    MCGCH2hhcmJvci5oYXJib3Iuc3ZjLmNsdXN0ZXIubG9jYWwwDQYJKoZIhvcNAQEL
    BQADggIBAFJmA8uq6JVr51ULJfMR/PA/dubVyMAGze1agIBSMLArzGhGa8xZBVNq
    woTDyUsmvAYXaUIHp/dX2T/YJ7919RF3jVRfn5NnfEYIXf/kM9QOSgsbXPcZg9zV
    Mz4Z/ktf2lIvvr2jwY8wPcvB6xkok59TkNG6aoz+hTpRUgrjdn4jt+aejXfIAakH
    cCTBvV34B9uaN/xQQk+2VjRzoNLzK1yk12d1wNUJZpoaD/MLxOEIXQc/bqmt4OQJ
    c434/WMTodnsFYl9WMouCn4KvZbn69bdpzPfCzjna6N+GMwaCjAOqiF8YK5rrkK9
    paHnokRDyQNYcDtT6yw1a076KORyVQip5E9Iv10uAlkXgkQTEwwZSX+ELu0DrnJV
    5xkEO9OIBFW/up59qOgiKyWsKT1ZdqKIrPkf/kFU9Hm7okaeXUrUV+kZIQzdoss6
    OcQFc9XzmG9aJBC+8zqiDFP9qH42Qwti9G7P6mspK5+dw7dLE9dnYTaEqH79LrX8
    PZCRw1FTM47eFOfcE1VY6aGwipO3ROCS0u26FJi6jjMoUkyRtOqhLgQXWEV271+R
    nmuaIBTnsG9igHnJi5pQNAjkdkgckgRqTfV8Uxwojj0C5rb0KXNI+RK7BCQQyqnT
    KBbm0rrb2Snz8uV5dXCYI+pRw62httiRTIXxZ0zyqQ1d7SPrwEaV
    -----END CERTIFICATE-----
